### ISSUE TITLE
Manual deployment step failed: OpenAI

### ISSUE THREAD

**Issue by adanbrownpaca** [Azure/aihub#54] opened 2024-05-29 16:30 UTC
The following deployment step failed for me:

az openai create --name aihub-openai --resource-group aihub-rg --location westeurope

Error:
'openai' is misspelled or not recognized by the system.

**Comment by rliberoff** [comment] 2024-05-31 10:36
Hi @adanbrownpaca,

Thank you for letting us know about this. 

The issues is related to outdated documentation. We will update the documentation shortly.

In the meantime, we consider this issue as duplicate of #53

**Closed by rliberoff** 2024-05-31 10:36 UTC
